services:
  windows-packager:
    image: zedmanny/windows-packager:latest
    container_name: windows-packager
    restart: unless-stopped

    ports:
      - "8080:8080"
      - "5900:5900"   # VNC display :0

    devices:
      - /dev/kvm:/dev/kvm

    volumes:
      - /opt/windows-packager/data:/data
